# Generated by Django 4.0.5 on 2022-06-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, default=None, max_length=30)),
                ('title', models.CharField(blank=True, default=None, max_length=150)),
                ('category', models.CharField(blank=True, default=None, max_length=30)),
                ('autor', models.CharField(blank=True, default=None, max_length=100)),
                ('image', models.CharField(blank=True, default=None, max_length=250)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('views', models.IntegerField()),
                ('language', models.CharField(blank=True, default=None, max_length=10)),
                ('history', models.CharField(blank=True, default=None, max_length=30)),
                ('dominio', models.CharField(blank=True, default=None, max_length=100)),
                ('link', models.CharField(blank=True, default=None, max_length=250)),
                ('link_autor', models.CharField(blank=True, default=None, max_length=250)),
                ('body_news', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
